// ui/src/base/StatTile.vue
<script setup lang="ts">
import { TrendingDown, TrendingUp } from "@lucide/vue";
import { computed } from "vue";

import { Badge } from "@/components/ui/badge";
import {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import Sparkline from "./Sparkline.vue";

/**
 * A KPI tile: label, big value, trend against a stated comparison window, and
 * a sparkline. The comparison line is not decoration -- a number without a
 * baseline cannot be acted on, so `compare` is required.
 *
 * trend > 0 renders as an increase. `goodDirection` says whether that is good,
 * because rising latency and rising success rate are not the same news.
 *
 * The headline value is rendered whatever its type, including 0 and "": a tile
 * that showed a label and a comparison line with no number above them read as
 * a broken dashboard on every fresh install.
 */
const props = withDefaults(
  defineProps<{
    label: string;
    value: string | number;
    unit?: string;
    trend?: number | null;
    compare: string;
    series?: number[];
    goodDirection?: "up" | "down";
  }>(),
  { series: () => [], goodDirection: "up" },
);

const dir = computed(() =>
  props.trend == null ? null : props.trend >= 0 ? "up" : "down",
);
const good = computed(() =>
  dir.value == null ? null : dir.value === props.goodDirection,
);
const trendIcon = computed(() =>
  dir.value === "up" ? TrendingUp : TrendingDown,
);
const trendLabel = computed(() => `${Math.abs(props.trend ?? 0).toFixed(1)}%`);
</script>

<template>
  <Card>
    <CardHeader>
      <CardTitle>{{ props.label }}</CardTitle>
      <CardDescription v-if="props.compare">{{
        props.compare
      }}</CardDescription>
      <CardAction v-if="dir">
        <Badge :variant="good ? 'ok' : 'danger'">
          <component :is="trendIcon" />
          {{ trendLabel }}
        </Badge>
      </CardAction>
    </CardHeader>
    <CardContent>
      <div class="text-3xl font-semibold tracking-[-0.03em]">
        {{ props.value
        }}<span v-if="props.unit" class="ml-1 text-lg text-fg-muted">{{
          props.unit
        }}</span>
      </div>
      <Sparkline
        v-if="props.series.length > 1"
        :series="props.series"
        :stroke="good === false ? 'var(--danger)' : 'var(--ok)'"
      />
    </CardContent>
  </Card>
</template>

// ui/src/base/statTile.jsx
import { h } from "preact";
import { Icon } from "./icons.jsx";

/**
 * A KPI tile: label, big value, trend against a stated comparison window, and
 * a sparkline. The comparison line is not decoration -- a number without a
 * baseline cannot be acted on, so `compare` is required.
 *
 * trend > 0 renders as an increase. `goodDirection` says whether that is good,
 * because rising latency and rising success rate are not the same news.
 *
 * The headline value is rendered whatever its type, including 0 and "": a tile
 * that showed a label and a comparison line with no number above them read as
 * a broken dashboard on every fresh install.
 */
export function StatTile({ label, value, unit, trend, compare, series = [], goodDirection = "up" }) {
  const dir = trend == null ? null : trend >= 0 ? "up" : "down";
  const good = dir == null ? null : dir === goodDirection;

  return (
    <div className="card stat">
      <div className="stat-head">
        <span className="stat-label">{label}</span>
        {dir ? (
          <span className={`stat-trend ${good ? "up" : "down"}`}>
            <Icon name={dir === "up" ? "trendUp" : "trendDown"} size={13} />
            {`${Math.abs(trend).toFixed(1)}%`}
          </span>
        ) : null}
      </div>
      <div className="stat-value">
        {value}
        {unit ? <span className="stat-unit">{unit}</span> : null}
      </div>
      {compare ? <div className="stat-compare">{compare}</div> : null}
      {series.length > 1 ? <Sparkline series={series} stroke={good === false ? "var(--danger)" : "var(--ok)"} /> : null}
    </div>
  );
}

/**
 * Inline SVG sparkline. Shows shape, not exact values -- the tile's headline
 * number carries the precision.
 */
export function Sparkline({ series, stroke = "var(--ok)", width = 220, height = 34 }) {
  const max = Math.max(...series, 1);
  const min = Math.min(...series, 0);
  const span = max - min || 1;
  const step = series.length > 1 ? width / (series.length - 1) : width;

  const points = series
    .map((v, i) => `${(i * step).toFixed(1)},${(height - ((v - min) / span) * height).toFixed(1)}`)
    .join(" ");

  return (
    <svg className="spark" viewBox={`0 0 ${width} ${height}`} preserveAspectRatio="none" aria-hidden="true">
      <polyline
        points={points}
        fill="none"
        stroke={stroke}
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
        vector-effect="non-scaling-stroke"
      />
    </svg>
  );
}
